//Defines the parameters of our Valleytronics Architecture.
////////////////////////////////////////////////////////////////
//
//
#define arch_  8 //Sets the architecture Should stay as 8 for now.
                 //
#define V_S   10 //Defines the source voltage for the valley gates. Any positive value will do due to 
	         //Due to the large resistance generated by valleytronics.
                 //
#define Vref_ 10 //Defines the reference voltage for the gate operations. Usually try and match source voltage
		 //for simplicity, but any positive number will do.
//////////////////////////////////////////////////////////////////
